# Generated by Django 4.1.2 on 2022-10-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comet_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet_assistant.action')),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet_auth.userinformation')),
            ],
        ),
        migrations.CreateModel(
            name='DialogueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.TextField()),
                ('writer', models.TextField()),
                ('date', models.DateTimeField()),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet_auth.userinformation')),
            ],
        ),
    ]
