# Generated by Django 4.1.2 on 2022-11-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comet_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialoguehistory',
            old_name='writer',
            new_name='message_writer',
        ),
    ]
