# Generated by Django 4.1.2 on 2022-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet_assistant', '0002_rename_writer_dialoguehistory_message_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguehistory',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialoguehistory',
            name='more_info',
            field=models.TextField(null=True),
        ),
    ]
