# Generated by Django 4.1.2 on 2022-12-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet_assistant', '0004_rename_cleared_dialoguehistory_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguehistory',
            name='response_error',
            field=models.BooleanField(default=False),
        ),
    ]
