# Generated by Django 4.1.2 on 2022-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='problem_id',
            field=models.IntegerField(default=1),
        ),
    ]
