# Generated by Django 4.1.2 on 2022-10-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet_auth', '0002_userinformation_problem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='design_evaluator_instance_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='design_evaluator_request_queue_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='design_evaluator_request_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='design_evaluator_response_queue_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='design_evaluator_response_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='design_evaluator_service_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='genetic_algorithm_instance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='genetic_algorithm_request_queue_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='genetic_algorithm_request_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='genetic_algorithm_response_queue_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='genetic_algorithm_response_queue_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='genetic_algorithm_service_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='service_lock',
            field=models.BooleanField(default=False),
        ),
    ]
