# Generated by Django 4.1.2 on 2022-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet_auth', '0004_alter_userinformation_design_evaluator_instance_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='design_evaluator_instance_count',
            field=models.IntegerField(default=3),
        ),
    ]
