# Generated by Django 4.1.2 on 2022-11-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet_auth', '0007_alter_userinformation_dataset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='genetic_algorithm_instance_count',
            field=models.IntegerField(default=1),
        ),
    ]
