# Generated by Django 4.1.2 on 2022-10-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet_problem', '0003_dataset_architecture_origin_userproblem_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
