# Generated by Django 4.1.2 on 2023-01-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comet_problem', '0005_objective_bounds_objective_optimization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet_problem.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ComputedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('explanation', models.TextField(default=None, null=True)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet_problem.architecture')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comet_problem.computed')),
            ],
        ),
    ]
