# Generated by Django 4.1.2 on 2023-01-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comet_problem', '0006_computed_computedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='computed',
            name='aliases',
            field=models.TextField(default=None, null=True),
        ),
    ]
